import { Button } from "@/components/buttons/Button";
import { Card, CardBody } from "@/components/cards/Card";
import { DeviceMockup } from "@/components/examples/DeviceMockup";
import { DocsShell } from "@/components/navigation/DocsShell";
import { DataTable } from "@/components/table/DataTable";

function AnalyticsSummary({ mobile = false }: { mobile?: boolean }) {
  return <div className="min-w-0"><div className="mb-8 flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow mb-3">Analytics overview</p><h2 className={`${mobile ? "text-2xl" : "text-3xl"} font-extrabold tracking-[-0.04em]`}>Product signals</h2><p className="body-copy mt-2 text-sm">A focused view of the work shaping this month&apos;s outcomes.</p></div><Button variant="secondary">12 Sep 2026 <span aria-hidden="true">⌄</span></Button></div><div className="mb-6 flex gap-2 overflow-x-auto border-b border-[var(--color-border-default)]"><button type="button" className="whitespace-nowrap border-b-2 border-[var(--color-action-accent)] px-2 py-3 text-sm font-bold">Overview</button><button type="button" className="whitespace-nowrap px-2 py-3 text-sm font-semibold text-[var(--color-content-muted)]">Acquisition</button><button type="button" className="whitespace-nowrap px-2 py-3 text-sm font-semibold text-[var(--color-content-muted)]">Retention</button></div><div className={`grid gap-3 ${mobile ? "grid-cols-1" : "md:grid-cols-4"}`}>{[["Active users", "18,420", "+8.2%"], ["Completion", "72.8%", "+3.1%"], ["Time to value", "4.2m", "-0.6m"], ["Signals", "46", "8 new"]].map(([label, value, change]) => <Card key={label}><CardBody><p className="eyebrow mb-2">{label}</p><p className="m-0 text-3xl font-extrabold">{value}</p><p className="mt-2 text-sm font-semibold text-[var(--color-action-accent-dark)]">{change}</p></CardBody></Card>)}</div><section className="mt-8"><div className="mb-4 flex flex-wrap items-end justify-between gap-4"><div><p className="eyebrow mb-2">Signal detail</p><h3 className="m-0 text-xl font-bold">Latest product work</h3></div><Button variant="tertiary">Download CSV <span aria-hidden="true">↓</span></Button></div><DataTable compact={mobile} /></section></div>;
}

export default function AnalyticsPage() {
  return <DocsShell><div className="max-w-6xl"><section className="mb-12 max-w-3xl"><p className="eyebrow mb-4">In practice / analytics</p><h1 className="text-4xl font-extrabold tracking-[-0.04em] md:text-6xl">A clear view of product signals.</h1><p className="body-copy mt-5 text-lg">This example demonstrates a reporting view that helps a product team scan performance, compare trends, and move from a high-level signal into detailed work.</p><div className="mt-6 grid gap-4 border-t border-[var(--color-border-default)] pt-5 sm:grid-cols-2"><div><p className="eyebrow mb-2">What the system contributes</p><p className="body-copy m-0 text-sm">Metric cards establish hierarchy, tabs organize the report, and table controls make the underlying detail actionable.</p></div><div><p className="eyebrow mb-2">Patterns in use</p><p className="body-copy m-0 text-sm">Date action, tabs, metric cards, tertiary export action, filtering, sorting, and responsive overflow.</p></div></div></section><section aria-labelledby="analytics-preview-heading"><div className="mb-5"><p className="eyebrow mb-2">Rendered example</p><h2 id="analytics-preview-heading" className="m-0 text-2xl font-bold">Analytics overview</h2></div><DeviceMockup label="Desktop / 1440px"><AnalyticsSummary /></DeviceMockup><div className="mt-10 flex justify-center"><DeviceMockup label="Mobile / 390px" mode="mobile"><AnalyticsSummary mobile /></DeviceMockup></div></section></div></DocsShell>;
}
