import { Card, CardBody, CardFooter, CardHeader } from "@/components/cards/Card";
import { CardImage } from "@/components/cards/CardImage";
import { CodeTabs } from "@/components/documentation/CodeTabs";
import { ComponentPage } from "@/components/documentation/ComponentPage";

const cssCode = `.card {\n  border: 1px solid var(--border-default);\n  border-radius: 16px;\n  background: white;\n}`;

export default function CardsPage() {
   return <ComponentPage name="Cards" eyebrow="Components / grouping" description="Cards create a composed surface for information that belongs together, from a single metric to a decision-ready work item." usage={<p className="m-0">Use a card to group related content with a clear boundary. Cards can be independent articles, or they can contain one clear action without nesting interactive controls.</p>} contract={["Use Card with CardImage, CardHeader, CardBody, and CardFooter parts.", "Modes include default, hover, selected, and disabled.", "Keep one clear interactive action per card.", "Use equal-height cards when comparing items in a grid."]} accessibility={["Do not nest links or buttons inside another interactive element.", "Use meaningful headings for card groups.", "Keep status information available as text, not color alone.", "Provide useful alt text for CardImage content."]} examples={[{ title: "Metric card", description: "A compact value with context and a supporting action.", content: <CodeTabs view={<Card><CardHeader><div><p className="eyebrow mb-2">Metric card</p><h3 className="m-0 text-xl font-bold">Activation rate</h3></div><span className="rounded-full bg-[var(--color-surface-raised)] px-2 py-1 text-xs font-semibold">+12%</span></CardHeader><CardBody><p className="m-0 text-5xl font-extrabold">68.4%</p><p className="body-copy mt-2 text-sm">Compared with the previous 30 days.</p></CardBody><CardFooter><span className="text-sm font-semibold">View trend ↗</span></CardFooter></Card>} cssCode={cssCode} javascriptCode={'<Card><CardBody>...</CardBody></Card>'} /> }, { title: "Media and interaction modes", description: "Image, selected, hover, and disabled states are composable.", content: <div className="grid gap-4 md:grid-cols-2"><CodeTabs view={<Card><CardImage src="/card-image.svg" alt="Abstract orange and charcoal landscape" /><CardBody><p className="m-0 font-bold">Media card</p></CardBody></Card>} cssCode={cssCode} javascriptCode={'<Card><CardImage src="/card-image.svg" alt="..." /></Card>'} /><CodeTabs view={<div className="grid gap-3"><Card mode="hover"><CardBody><p className="m-0 font-bold">Hover state</p></CardBody></Card><Card mode="selected"><CardBody><p className="m-0 font-bold">Selected state</p></CardBody></Card><Card mode="disabled"><CardBody><p className="m-0 font-bold">Disabled state</p></CardBody></Card></div>} cssCode={cssCode} javascriptCode={'<Card mode="selected">...</Card>'} /></div> }]} />;
}
