import { CodeTabs } from "@/components/documentation/CodeTabs";
import { ComponentPage } from "@/components/documentation/ComponentPage";
import { DataTable } from "@/components/table/DataTable";
import { Table, TableBody, TableCell, TableColumnHeader, TableHead, TableRow } from "@/components/table/Table";

const cssCode = `table {\n  width: 100%;\n  border-collapse: collapse;\n}\nth { text-align: left; }`;

export default function TablePage() {
    return <ComponentPage name="Table" eyebrow="Components / data" description="Table presents dense information with semantic structure, predictable controls, and resilient loading, empty, and responsive states." usage={<p className="m-0">Use a table when people need to compare values across consistent records. Keep filters and actions close to the table, then preserve the table relationship on small screens with intentional overflow.</p>} contract={["Use real table, caption, thead, tbody, th, and td elements.", "Compose low-level Table, TableHead, TableRow, TableColumnHeader, and TableCell parts when markup needs custom behavior.", "Use DataTable as the higher-level pattern for common sorting, filtering, and selection.", "Filtering, empty, and loading states are part of the component contract."]} accessibility={["Use scoped column and row headers.", "Keep a visually hidden caption for context.", "Give every selection control an accessible row-specific label.", "Do not replace genuinely tabular data with CSS grid."]} examples={[{ title: "Table structure", description: "The low-level parts preserve native table semantics.", content: <CodeTabs view={<Table><caption className="sr-only">Example table structure</caption><TableHead><TableRow><TableColumnHeader>Project</TableColumnHeader><TableColumnHeader>Owner</TableColumnHeader></TableRow></TableHead><TableBody><TableRow><th scope="row" className="px-4 py-4 font-semibold">Fieldwork</th><TableCell>Mika Lee</TableCell></TableRow></TableBody></Table>} cssCode={cssCode} javascriptCode={'<Table><TableHead>...</TableHead><TableBody>...</TableBody></Table>'} /> }, { title: "DataTable behavior", description: "A higher-level table with filtering, sorting, and row selection.", content: <CodeTabs view={<DataTable />} cssCode={cssCode} javascriptCode={'<DataTable columns={columns} rows={rows} />'} /> }, { title: "Compact responsive table", description: "The same data pattern inside a narrower product surface.", content: <CodeTabs view={<DataTable compact />} cssCode={cssCode} javascriptCode={'<DataTable compact columns={columns} rows={rows} />'} /> }]} />;
}
